-- Generated corrections for false true/false questions (Subiectul I-D)
-- Each correction rewrites the false statement to make it true, without using negation.

UPDATE questions SET false_correction = 'În procesul de eliminare, urina trece din uretere în vezica urinară.' WHERE id = '3f2b29fa7af27a22';
UPDATE questions SET false_correction = 'Segmentul periferic al analizatorului auditiv este localizat în urechea internă.' WHERE id = '1cee13e7a9fc8ed8';
UPDATE questions SET false_correction = 'Fasciculele spino-bulbare conduc sensibilitatea tactilă fină (epicritică).' WHERE id = '9561bd788894117e';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este reprezentat de aria auditivă din lobul temporal al scoarței cerebrale.' WHERE id = 'b817273877e6abb2';
UPDATE questions SET false_correction = 'În procesul de eliminare la exterior, urina trece din vezica urinară în uretră.' WHERE id = '406613b4f15cbc36';
UPDATE questions SET false_correction = 'Coxalele sunt oase ale centurii pelviene (membrelor inferioare).' WHERE id = '1003f46b05b47401';
UPDATE questions SET false_correction = 'Receptorii pentru auz sunt localizaţi în urechea internă.' WHERE id = 'a89a8a4d46049716';
UPDATE questions SET false_correction = 'Urina din vezica urinară este eliminată la exterior prin uretră.' WHERE id = 'dd48dc0f7de5c669';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este localizat în aria auditivă din scoarța cerebrală (lobul temporal).' WHERE id = 'd5f661572c815f23';
UPDATE questions SET false_correction = 'În timpul unei inspiraţii normale, presiunea aerului din plămâni scade.' WHERE id = '90e5896311abe89d';
UPDATE questions SET false_correction = 'Sistemul nervos vegetativ are o componentă simpatică și o componentă parasimpatică.' WHERE id = '60d50db72df0842c';
UPDATE questions SET false_correction = 'În procesul eliminării la exterior, urina din vezica urinară trece în uretră.' WHERE id = '0b4c72a54734aeaf';
UPDATE questions SET false_correction = 'Tibia este os al membrului inferior, iar omoplatul este os al centurii scapulare.' WHERE id = '6e210e89679ab70a';
UPDATE questions SET false_correction = 'Nefronul este unitatea morfo-funcțională a rinichiului, la nivelul acestuia formându-se urina.' WHERE id = '4db2ef09c67c8e83';
UPDATE questions SET false_correction = 'Produşii finali ai digestiei glucidelor şi proteinelor se obţin în intestinul subţire.' WHERE id = '178bd6ea69e5682e';
UPDATE questions SET false_correction = 'Receptorii analizatorului vestibular sunt localizați în urechea internă.' WHERE id = '6ef4f23b2b0d1eb4';
UPDATE questions SET false_correction = 'Insulina este unul dintre hormonii secretaţi de pancreas (pancreasul endocrin).' WHERE id = '0814a502b16b2fb8';
UPDATE questions SET false_correction = 'Capacitatea vitală reprezintă suma a trei volume respiratorii: volumul curent, volumul inspirator de rezervă, volumul expirator de rezervă.' WHERE id = '546f56e801922089';
UPDATE questions SET false_correction = 'Enterocolita este boală a sistemului digestiv.' WHERE id = '7d4045339ceb8306';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este localizat în aria auditivă din scoarța cerebrală (lobul temporal).' WHERE id = 'a5c875cc8f5a1aa5';
UPDATE questions SET false_correction = 'Ovarul reprezintă gonada feminină.' WHERE id = 'e802dc83784b0cc2';
UPDATE questions SET false_correction = 'Pepsina face parte din compoziția chimică a sucului gastric.' WHERE id = '4cbfde4c746c6c22';
UPDATE questions SET false_correction = 'Celulele cu conuri sunt receptorii pentru vederea diurnă (colorată), iar celulele cu bastonaşe sunt receptorii pentru vederea nocturnă (crepusculară).' WHERE id = '6c2d6308822232d9';
UPDATE questions SET false_correction = 'Tarsienele sunt oase ale membrului inferior, iar carpienele sunt oase ale membrului superior.' WHERE id = '45a903c63982f185';
UPDATE questions SET false_correction = 'Senzația auditivă se formează la nivelul segmentului central al analizatorului auditiv (aria auditivă din scoarța cerebrală).' WHERE id = 'f7d87cb234469817';
UPDATE questions SET false_correction = 'Osul femur aparține scheletului membrului inferior.' WHERE id = '7df48eda30e9a759';
UPDATE questions SET false_correction = 'Sternocleidomastoidienii sunt muşchi ai gâtului.' WHERE id = '5ddf04ccc4692b9d';
UPDATE questions SET false_correction = 'Ficatul secretă bila, un suc digestiv cu rol în emulsionarea lipidelor, dar care este lipsit de enzime.' WHERE id = '3bd093a02baca8f2';
UPDATE questions SET false_correction = 'Simpaticul şi parasimpaticul sunt componente ale sistemului nervos vegetativ.' WHERE id = '82b5acb417394f0c';
UPDATE questions SET false_correction = 'Celulele cu conuri reprezintă segmentul periferic al analizatorului vizual.' WHERE id = 'e17f110002ffd8b4';
UPDATE questions SET false_correction = 'Stomacul secretă un suc digestiv (sucul gastric) din compoziția căruia fac parte enzime (pepsina).' WHERE id = 'd2feefe40f804231';
UPDATE questions SET false_correction = 'Urechea internă reprezintă sediul receptorilor auditivi, iar senzaţia auditivă se formează la nivelul ariei auditive din scoarța cerebrală.' WHERE id = '134f9e2ac6eeaee6';
UPDATE questions SET false_correction = 'Sângele oxigenat din ventriculul stâng al inimii este propulsat în artera aortă.' WHERE id = 'a1d112fa7e1d3f91';
UPDATE questions SET false_correction = 'Celulele cu conuri din structura retinei asigură vederea cromatică (colorată).' WHERE id = '62eacb1ed11c9458';
UPDATE questions SET false_correction = 'Receptorii analizatorului vestibular reprezintă segmentul periferic al acestui analizator.' WHERE id = '0a868429de89724a';
UPDATE questions SET false_correction = 'Anexita este afecțiune a sistemului reproducător, iar glomerulonefrita este afecțiune a sistemului excretor.' WHERE id = '810655c08fb6ad6a';
UPDATE questions SET false_correction = 'Celulele cu conuri sunt receptorii pentru vederea diurnă și vederea colorată.' WHERE id = '53d87fe3532883df';
UPDATE questions SET false_correction = 'Prostata este o glandă anexă a aparatului genital masculin.' WHERE id = '6a43b0b8761d0262';
UPDATE questions SET false_correction = 'Produşii finali ai digestiei glucidelor se obţin în intestinul subţire.' WHERE id = 'ef21230b6927ba66';
UPDATE questions SET false_correction = 'Celulele cu conuri sunt receptorii pentru vederea diurnă (colorată).' WHERE id = '51e47df87fabb4fb';
UPDATE questions SET false_correction = 'Bila este secretată de ficat.' WHERE id = '6e9f3d31ada2d686';
UPDATE questions SET false_correction = 'Sucul pancreatic este secretat de partea exocrină a pancreasului.' WHERE id = '1627a3efaf1c1cc0';
UPDATE questions SET false_correction = 'Falangele și tarsienele sunt oase ale membrului inferior, iar carpienele sunt oase ale membrului superior.' WHERE id = 'ba3a2427960c62df';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este reprezentat de aria auditivă din scoarța cerebrală (lobul temporal).' WHERE id = '91ff097365f634d6';
UPDATE questions SET false_correction = 'Sistemul nervos central este alcătuit din encefal şi măduva spinării.' WHERE id = 'e36afc66bc387bcd';
UPDATE questions SET false_correction = 'Urina finală/definitivă este rezultatul proceselor de filtrare glomerulară, reabsorbție tubulară și secreție tubulară.' WHERE id = '8e5dd8193fd705b3';
UPDATE questions SET false_correction = 'Uretra este calea urinară care preia urina din vezica urinară și o elimină la exterior.' WHERE id = 'aa5cfdad236403be';
UPDATE questions SET false_correction = 'Receptorii analizatorului vizual sunt localizați în retină.' WHERE id = 'ded121f860d0d91e';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este localizat la nivelul ariei auditive din scoarța cerebrală.' WHERE id = 'f6be9553fb646acd';
UPDATE questions SET false_correction = 'Volumul rezidual este volumul de aer care rămâne în plămâni după o expirație forțată și nu este componentă a capacităţii vitale.' WHERE id = '27948fa14e7f1314';
UPDATE questions SET false_correction = 'Fasciculele spinobulbare conduc sensibilitatea tactilă fină (epicritică) și sensibilitatea proprioceptivă conștientă.' WHERE id = '3adf849d4686f897';
UPDATE questions SET false_correction = 'Stomatita este afecţiune a sistemului digestiv, iar cistita este afecțiune a sistemului excretor.' WHERE id = '1e0120f0a53fe0da';
UPDATE questions SET false_correction = 'Stimularea sistemului nervos vegetativ parasimpatic are ca efect micșorarea (constricția) pupilei.' WHERE id = '54b8ff3b2aa0e3af';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului vestibular este reprezentat de aria vestibulară din scoarța cerebrală.' WHERE id = 'fcc2d15574d03a3d';
UPDATE questions SET false_correction = 'Una dintre glandele anexe ale aparatului genital masculin este prostata.' WHERE id = '25939304b3d746ff';
UPDATE questions SET false_correction = 'Celulele cu bastonașe sunt receptori ai vederii nocturne (crepusculare).' WHERE id = '3ac61bd827fc50e0';
UPDATE questions SET false_correction = 'Entorsele şi luxaţiile sunt afecţiuni ale sistemului osos.' WHERE id = 'caeff4ac97063139';
UPDATE questions SET false_correction = 'Sternocleidomastoidienii sunt muşchi ai gâtului.' WHERE id = '17b75a13d5cb36e4';
UPDATE questions SET false_correction = 'În procesul de eliminare, urina din vezica urinară trece în uretră.' WHERE id = '19d00d561e392233';
UPDATE questions SET false_correction = 'Emfizemul este afecțiune a sistemului respirator.' WHERE id = 'e5192356a3ac14c4';
UPDATE questions SET false_correction = 'Simpaticul şi parasimpaticul sunt componente ale sistemului nervos vegetativ.' WHERE id = 'e863786c281aa089';
UPDATE questions SET false_correction = 'Sistemul endocrin, alcătuit din glandele endocrine, participă la realizarea funcției de reglare a organismului.' WHERE id = '80e1f257b753076b';
UPDATE questions SET false_correction = 'Adenomul de prostată este afecțiune a sistemului reproducător masculin, iar anexita este afecțiune a sistemului reproducător feminin.' WHERE id = 'd041f4e9d5f47a81';
UPDATE questions SET false_correction = 'Prin venele pulmonare circulă sânge oxigenat.' WHERE id = 'f87c6288fc072a3a';
UPDATE questions SET false_correction = 'Capacitatea pulmonară (totală) reprezintă suma dintre capacitatea vitală şi volumul rezidual.' WHERE id = '1d0cb1ff85ece28b';
UPDATE questions SET false_correction = 'Pancreasul exocrin secretă suc pancreatic, cu rol digestiv.' WHERE id = 'd7d9beeb4a79e70a';
UPDATE questions SET false_correction = 'Sucul gastric conține enzime (pepsina).' WHERE id = '9f86f47b30366636';
UPDATE questions SET false_correction = 'Anexita este afecțiune a sistemului reproducător, iar nefrita este afecțiune a sistemului excretor.' WHERE id = '93420b36921d43fa';
UPDATE questions SET false_correction = 'Creșterea frecvenței cardiace este un efect al stimulării sistemului nervos vegetativ simpatic.' WHERE id = '40d91d36c85307a0';
UPDATE questions SET false_correction = 'Ureterul este componentă a sistemului excretor (urinar).' WHERE id = '895bfee94a38c9a0';
UPDATE questions SET false_correction = 'Urina din vezica urinară este eliminată la exterior prin uretră.' WHERE id = 'd316b7c233333afb';
UPDATE questions SET false_correction = 'În timpul unei expirații normale, presiunea aerului din plămâni crește.' WHERE id = '696e7af7c92d3329';
UPDATE questions SET false_correction = 'Ficatul secretă un suc digestiv numit bilă, care este lipsit de enzime digestive și are rol în emulsionarea grăsimilor.' WHERE id = 'c2d974ad6d7081e3';
UPDATE questions SET false_correction = 'Senzația auditivă se formează la nivelul segmentului central al analizatorului auditiv (aria auditivă din scoarța cerebrală).' WHERE id = '6238de917bea5127';
UPDATE questions SET false_correction = 'Fasciculele spino-bulbare conduc sensibilitatea tactilă fină (epicritică).' WHERE id = '6caa0fa45785db7a';
UPDATE questions SET false_correction = 'Uretra este calea urinară care preia urina din vezica urinară și o elimină la exterior.' WHERE id = '6d65e89750ef988d';
UPDATE questions SET false_correction = 'Segmentul intermediar al analizatorului vizual conține căi senzitivo-senzoriale care conduc impulsul nervos.' WHERE id = 'd37e7d8f3ae692c4';
UPDATE questions SET false_correction = 'Uretra preia urina din vezica urinară și o elimină la exterior.' WHERE id = '20ea98e754aed003';
UPDATE questions SET false_correction = 'Aminoacizii sunt produşii finali ai digestiei proteinelor.' WHERE id = '19cec4c4ecd27f34';
UPDATE questions SET false_correction = 'Coma este o disfuncție nervoasă (neurologică).' WHERE id = 'f246795a6338c436';
UPDATE questions SET false_correction = 'Prostata este glandă anexă a aparatului genital masculin.' WHERE id = '8957ff9f3885ac29';
UPDATE questions SET false_correction = 'Urina din vezica urinară este eliminată la exterior prin uretră.' WHERE id = '5ac61334264baefe';
UPDATE questions SET false_correction = 'Receptorii vestibulari reprezintă segmentul periferic al analizatorului vestibular, iar senzaţia de echilibru se formează la nivelul segmentului central.' WHERE id = 'f571bef385358f2f';
UPDATE questions SET false_correction = 'În timpul unei inspirații forțate, presiunea aerului din plămâni scade.' WHERE id = '891b71bdd6b2ae68';
UPDATE questions SET false_correction = 'Fotoreceptorii sunt reprezentați de celulele cu conuri și celulele cu bastonașe din structura retinei.' WHERE id = '9706966deddf5378';
UPDATE questions SET false_correction = 'Ovarul este gonada (glanda reproducătoare) feminină.' WHERE id = '48e65cb5cc7ab0bf';
UPDATE questions SET false_correction = 'Celulele cu bastonașe conțin pigmentul fotosensibil rodopsina.' WHERE id = '38c1f62626194fdf';
UPDATE questions SET false_correction = 'Reducerea frecvenței cardiace este un efect al stimulării sistemului nervos vegetativ parasimpatic.' WHERE id = '114876d1e31b9794';
UPDATE questions SET false_correction = 'Urechea medie transmite vibrațiile sonore de la timpan la urechea internă prin lanțul de oscioare.' WHERE id = 'b93457033f9f6d9c';
UPDATE questions SET false_correction = 'Cele două componente ale sistemului nervos vegetativ sunt simpaticul și parasimpaticul.' WHERE id = 'ec8fe10dc3564c03';
UPDATE questions SET false_correction = 'Anexita este afecţiune a sistemului reproducător.' WHERE id = '8de0cae4ed4fbe90';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului cutanat este reprezentat de aria somatosenzorială din scoarța cerebrală.' WHERE id = '7b3c1cc47ba019e1';
UPDATE questions SET false_correction = 'Volumul rezidual este volumul de aer care rămâne în plămâni după o expirație forțată și nu face parte din capacitatea vitală.' WHERE id = '7afad166a272d8be';
UPDATE questions SET false_correction = 'Industrializarea și defrişarea sunt exemple de activităţi umane care pot contribui la degradarea unui ecosistem natural.' WHERE id = '9f479ce516e3e5f0';
UPDATE questions SET false_correction = 'Fasciculele spino-bulbare conduc sensibilitatea tactilă fină (epicritică).' WHERE id = 'b70ff0432c6565e6';
UPDATE questions SET false_correction = 'Urechea internă reprezintă segmentul periferic al analizatorului auditiv.' WHERE id = '47e914db6770bb02';
UPDATE questions SET false_correction = 'Prostata este glandă anexă a sistemului reproducător masculin.' WHERE id = '8f61a5565a068d7d';
UPDATE questions SET false_correction = 'Croitorul este unul dintre mușchii scheletici ai membrului inferior.' WHERE id = 'be4c6c6cec40231a';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului cutanat este localizat la nivelul ariei somatosenzoriale din scoarța cerebrală.' WHERE id = '93036a57266f4b57';
UPDATE questions SET false_correction = 'Prostata este componentă a sistemului reproducător masculin, iar vaginul este componentă a sistemului reproducător feminin.' WHERE id = '49a57e101fd51876';
UPDATE questions SET false_correction = 'Urina este depozitată în vezica urinară.' WHERE id = '346f1ce5d20ec808';
UPDATE questions SET false_correction = 'Enterocolitele sunt afecțiuni digestive.' WHERE id = '08378fe4767ae4d8';
UPDATE questions SET false_correction = 'Ovarul reprezintă gonada feminină.' WHERE id = 'b5468320371bceb8';
UPDATE questions SET false_correction = 'Din punct de vedere funcțional, sistemul nervos vegetativ se clasifică în simpatic şi parasimpatic.' WHERE id = 'e441cd4a72b18e8d';
UPDATE questions SET false_correction = 'Volumul curent, volumul inspirator de rezervă și volumul expirator de rezervă sunt componentele capacităţii vitale.' WHERE id = '30da2f25f3a329a8';
UPDATE questions SET false_correction = 'Omoplatul este os al centurii scapulare, iar tibia este os al membrului inferior.' WHERE id = '438b4200073544c5';
UPDATE questions SET false_correction = 'Căile ascendente medulare conduc impulsurile senzitive de la receptori spre centrii nervoși.' WHERE id = '16b16e8744f8dec8';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este localizat la nivelul ariei auditive din scoarța cerebrală (lobul temporal).' WHERE id = 'a2805ff23bbeb001';
UPDATE questions SET false_correction = 'În timpul unei expiraţii normale, volumul pulmonar scade.' WHERE id = 'ecd2815e9b45b7c8';
UPDATE questions SET false_correction = 'În procesul de eliminare, urina din vezica urinară trece în uretră.' WHERE id = 'b21393a399836f99';
UPDATE questions SET false_correction = 'În timpul unei expirații normale, presiunea aerului din plămâni crește.' WHERE id = 'be8c567c67050571';
UPDATE questions SET false_correction = 'Contracepţia constă într-un ansamblu de metode folosite de către bărbaţi sau de către femei pentru evitarea sarcinii.' WHERE id = '4b72c6a9e43d6d72';
UPDATE questions SET false_correction = 'Receptorii vestibulari reprezintă segmentul periferic al analizatorului vestibular.' WHERE id = '3b6cd4fc710f0e4b';
UPDATE questions SET false_correction = 'Celulele cu conuri asigură vederea colorată (cromatică).' WHERE id = 'c9049609b6fb0532';
UPDATE questions SET false_correction = 'Anexita este afecțiune a sistemului reproducător feminin.' WHERE id = '755e6675c25179ee';
UPDATE questions SET false_correction = 'Ovarele reprezintă gonadele (glandele reproducătoare) ale sistemului reproducător feminin.' WHERE id = 'f1d0a3c1ea3b918b';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului vizual este reprezentat de aria vizuală din scoarța cerebrală (lobul occipital).' WHERE id = '0fde90d209d6a400';
UPDATE questions SET false_correction = 'În procesul de eliminare, urina din vezica urinară trece în uretră.' WHERE id = 'ac74cc83f8ddce92';
UPDATE questions SET false_correction = 'Volumul rezidual este volumul de aer care rămâne în plămâni după expirația forțată și nu face parte din capacitatea vitală.' WHERE id = '7d375e8639ee2073';
UPDATE questions SET false_correction = 'Anexita este afecțiune a sistemului reproducător, iar cistita este afecțiune a sistemului excretor.' WHERE id = 'c61619735b000642';
UPDATE questions SET false_correction = 'Urina din vezica urinară este eliminată la exterior prin uretră.' WHERE id = '73da6337539ee61d';
UPDATE questions SET false_correction = 'Segmentul central al analizatorului auditiv este localizat la nivelul ariei auditive din scoarța cerebrală.' WHERE id = '782741489daa10c5';
UPDATE questions SET false_correction = 'Planul mediosagital este planul simetriei bilaterale a corpului.' WHERE id = '6507f45dfd80d4f3';
UPDATE questions SET false_correction = 'Fotoreceptorii retinieni transformă radiațiile luminoase în impulsuri nervoase.' WHERE id = 'd90339544d878285';
UPDATE questions SET false_correction = 'Stimularea parasimpaticului determină constricția (micșorarea) pupilei.' WHERE id = '5b5459a2cd17e446';
UPDATE questions SET false_correction = 'Receptorii analizatorului vizual sunt localizați în retină.' WHERE id = '1132c722b14eeb81';
UPDATE questions SET false_correction = 'Creșterea în lungime a oaselor se realizează pe seama cartilajului de creștere (cartilajul de conjugare).' WHERE id = '944c739253cc4bf5';
UPDATE questions SET false_correction = 'Nucleozomii conțin un miez format din proteine histonice.' WHERE id = '837d8670aa1af120';
UPDATE questions SET false_correction = 'Fibroza pulmonară este o boală cronică (degenerativă) a sistemului respirator.' WHERE id = '6ebb78aedcdf078e';
UPDATE questions SET false_correction = 'Căile descendente medulare sunt motorii.' WHERE id = 'e3f3117e5c14669d';
UPDATE questions SET false_correction = 'Urechea internă este sediul receptorului acustic.' WHERE id = '8d408d214c9459e9';
UPDATE questions SET false_correction = 'Bicepsul este muşchi scheletic, iar femurul este os.' WHERE id = 'adfdbc1445875650';
UPDATE questions SET false_correction = 'Planul transversal împarte corpul într-o parte superioară și una inferioară.' WHERE id = '8c29daf380578b79';
UPDATE questions SET false_correction = 'Nucleul conține materialul genetic la eucariote.' WHERE id = '7f690422e2463a62';
UPDATE questions SET false_correction = 'Segmentul periferic al analizatorului auditiv este localizat în urechea internă.' WHERE id = '1c5c653fa2835b6a';
UPDATE questions SET false_correction = 'Fasciculul spinotalamic anterior conduce sensibilitatea tactilă grosieră (protopatică).' WHERE id = 'fed2c9fee922c0b3';
UPDATE questions SET false_correction = 'Produşii finali ai digestiei glucidelor şi proteinelor se obţin în intestinul subţire.' WHERE id = 'a330053581414eec';
UPDATE questions SET false_correction = 'Receptorii analizatorului vestibular sunt localizați în urechea internă.' WHERE id = '135b520c8d620f9a';
